server:
  # Server bind address
  address: "${HTTP_BIND_ADDRESS:0.0.0.0}"
  # Server bind port
  port: "${HTTP_BIND_PORT:8081}"

spring:
  aop:
    proxy-target-class: true
  datasource:
    url: jdbc:mysql://39.104.165.155:3306/BUPT_IOT?useSSL=false
    username: root
    password: root
  redis:
#    url: redis://39.104.165.155:6379
    url: redis://127.0.0.1:6379
#    password: redis

oauth2:
    internal_client_id: client_1
    internal_client_secret: 123456
    external_client_id: client_2
    external_client_secret: 123456

    loginUrl: /api/v1/account/login
    checkUrl: /api/v1/account/check_token

security.jwt:
  tokenExpirationTime: "${JWT_TOKEN_EXPIRATION_TIME:900}" # Number of seconds (15 mins)
  refreshTokenExpTime: "${JWT_REFRESH_TOKEN_EXPIRATION_TIME:3600}" # Seconds (1 hour)
  tokenIssuer: "${JWT_TOKEN_ISSUER:bupt.edu.cn}"
  tokenSigningKey: "${JWT_TOKEN_SIGNING_KEY:SigningKey}"

account:
  host: 127.0.0.1
  port: ${server.port}
  check_url: http://${account.host}:${account.port}/api/v1/account/check_token
  login_url: http://${account.host}:${account.port}/api/v1/account/login
  client_id: client_2
  client_secret: 123456
  internal_client_id: client_1
  internal_client_secret: 123456