spring.thymeleaf.prefix: classpath:/template/
spring.thymeleaf.suffix: .html
spring.thymeleaf.mode: LEGACYHTML5
spring.thymeleaf.cache: true

spring:
  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb

server:
  # Server bind address
  address: "${HTTP_BIND_ADDRESS:0.0.0.0}"
  # Server bind port
  port: "${HTTP_BIND_PORT:8400}"

spring:
  aop:
    proxy-target-class: true
  datasource:
#  172.24.32.169
    url: jdbc:mysql://39.104.165.155:3306/BUPT_IOT?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    cachePrepStmts: true  # 开启二级缓存
  redis:
#    url: redis://39.104.165.155:6379
    url: redis://127.0.0.1:6379
#    password: redis

oauth2:
    internal_client_id: client_1
    internal_client_secret: 123456
    external_client_id: client_2
    external_client_secret: 123456

    loginUrl: /api/v1/account/login
    checkUrl: /api/v1/account/check_token

security.jwt:
  tokenExpirationTime: "${JWT_TOKEN_EXPIRATION_TIME:900}" # Number of seconds (15 mins)
  refreshTokenExpTime: "${JWT_REFRESH_TOKEN_EXPIRATION_TIME:3600}" # Seconds (1 hour)
  tokenIssuer: "${JWT_TOKEN_ISSUER:bupt.edu.cn}"
  tokenSigningKey: "${JWT_TOKEN_SIGNING_KEY:SigningKey}"

account:
  host: 0.0.0.0
  port: 8400
  check_url: http://0.0.0.0:8400/api/v1/account/check_token
  login_url: http://0.0.0.0:8400/api/v1/account/login
  client_id: client_2
  client_secret: 123456
  internal_client_id: client_1
  internal_client_secret: 123456

device-access:
# host: deviceaccess
# port: 8100
# delete_device_url: http://127.0.0.1:8100/api/v1/deviceaccess/devices/
# activate_device_url: http://127.0.0.1:8100/api/v1/deviceaccess/devices/activate/
# suspend_device_url: http://127.0.0.1:8100/api/v1/deviceaccess/devices/suspend/
 delete_device_url: http://deviceaccess:8100/api/v1/deviceaccess/devices/
 activate_device_url: http://deviceaccess:8100/api/v1/deviceaccess/devices/activate/
 suspend_device_url: http://deviceaccess:8100/api/v1/deviceaccess/devices/suspend/
